#!/bin/bash
# this adds test user for user interface tests
if test "$#" -ne 2; then
    echo "pass SuperuserName and SuperUserPassword"
fi

echo "from django.contrib.auth.models import User; User.objects.create_superuser('$1', 'admin@example.com', '$2')" | python manage.py shell